// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93nW7iwICIpvVHe1H1bOhNxXgfj1vH64',
    appId: '1:453130459630:web:4e11b549f788fd14f256ff',
    messagingSenderId: '453130459630',
    projectId: 'seatly-876ab',
    authDomain: 'seatly-876ab.firebaseapp.com',
    storageBucket: 'seatly-876ab.firebasestorage.app',
    measurementId: 'G-KLS1B9DQKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDitStBV6aQZ1GsnR8YDCoU2kri1-BVGY4',
    appId: '1:453130459630:android:f8c59ec53567c0fbf256ff',
    messagingSenderId: '453130459630',
    projectId: 'seatly-876ab',
    storageBucket: 'seatly-876ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__11tIKW8qQKHv9yNUoxMS8oqea51Iz4',
    appId: '1:453130459630:ios:33c3554b89bfe1d2f256ff',
    messagingSenderId: '453130459630',
    projectId: 'seatly-876ab',
    storageBucket: 'seatly-876ab.firebasestorage.app',
    iosBundleId: 'com.example.seatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD93nW7iwICIpvVHe1H1bOhNxXgfj1vH64',
    appId: '1:453130459630:web:24723e1d5530fdbcf256ff',
    messagingSenderId: '453130459630',
    projectId: 'seatly-876ab',
    authDomain: 'seatly-876ab.firebaseapp.com',
    storageBucket: 'seatly-876ab.firebasestorage.app',
    measurementId: 'G-D26SGJDWQ3',
  );
}
